apiVersion: v1
entries:
  spdk-csi:
  - apiVersion: v1
    appVersion: latest
    created: "2025-11-06T19:50:15.645551067Z"
    description: Simplyblock CSI Driver for Kubernetes
    digest: 40d0f8dd9bf31c8167fca9d5ccda8d6e14c3cbb379a076ab899f943f83c14613
    home: https://github.com/simplyblock-io/spdk-csi
    keywords:
    - spdk
    - csi
    - spdk-csi
    - simplyblock
    - controller
    name: spdk-csi
    sources:
    - https://github.com/simplyblock-io/spdk-csi/tree/master/charts/spdk-csi
    urls:
    - https://github.com/simplyblock-io/spdk-csi/raw/master/charts/spdk-csi/v0.3.24/spdk-csi-v0.3.24.tgz
    version: v0.3.24
  - apiVersion: v1
    appVersion: latest
    created: "2025-11-06T19:50:15.644480548Z"
    description: Simplyblock CSI Driver for Kubernetes
    digest: 63b4055b180e0a6ebf80a1ae06f9c23a37137b69449c6dd975dfed10a0902d89
    home: https://github.com/simplyblock-io/spdk-csi
    keywords:
    - spdk
    - csi
    - spdk-csi
    - simplyblock
    - controller
    name: spdk-csi
    sources:
    - https://github.com/simplyblock-io/spdk-csi/tree/master/charts/spdk-csi
    urls:
    - https://github.com/simplyblock-io/spdk-csi/raw/master/charts/spdk-csi/v0.3.23/spdk-csi-v0.3.23.tgz
    version: v0.3.23
  - apiVersion: v1
    appVersion: latest
    created: "2025-11-06T19:50:15.643413224Z"
    description: Simplyblock CSI Driver for Kubernetes
    digest: cbd0207cdfb4f16fd8a26a820ef558e65ed2cf80087086a6c8ecec581fb1a363
    home: https://github.com/simplyblock-io/spdk-csi
    keywords:
    - spdk
    - csi
    - spdk-csi
    - simplyblock
    - controller
    name: spdk-csi
    sources:
    - https://github.com/simplyblock-io/spdk-csi/tree/master/charts/spdk-csi
    urls:
    - https://github.com/simplyblock-io/spdk-csi/raw/master/charts/spdk-csi/v0.3.22/spdk-csi-v0.3.22.tgz
    version: v0.3.22
  - apiVersion: v1
    appVersion: latest
    created: "2025-11-06T19:50:15.642349337Z"
    description: Simplyblock CSI Driver for Kubernetes
    digest: b274263082859de994d611dc7890d77aa2095a84da69a73741d81a325568d6fe
    home: https://github.com/simplyblock-io/spdk-csi
    keywords:
    - spdk
    - csi
    - spdk-csi
    - simplyblock
    - controller
    name: spdk-csi
    sources:
    - https://github.com/simplyblock-io/spdk-csi/tree/master/charts/spdk-csi
    urls:
    - https://github.com/simplyblock-io/spdk-csi/raw/master/charts/spdk-csi/v0.3.21/spdk-csi-v0.3.21.tgz
    version: v0.3.21
  - apiVersion: v1
    appVersion: latest
    created: "2025-11-06T19:50:15.641252889Z"
    description: Simplyblock CSI Driver for Kubernetes
    digest: c3995eb4016ecb764272ee1cfc9779ced28dd8f7c53819539f41d71076478676
    home: https://github.com/simplyblock-io/spdk-csi
    keywords:
    - spdk
    - csi
    - spdk-csi
    name: spdk-csi
    sources:
    - https://github.com/simplyblock-io/spdk-csi/tree/master/charts/spdk-csi
    urls:
    - https://github.com/simplyblock-io/spdk-csi/raw/master/charts/spdk-csi/v0.3.20/spdk-csi-v0.3.20.tgz
    version: v0.3.20
  - apiVersion: v1
    appVersion: latest
    created: "2025-11-06T19:50:15.637722121Z"
    description: Simplyblock CSI Driver for Kubernetes
    digest: de203b9ace5c818cda9a2766e415ff5163cb3aafcc29c4e3bb28cd614491b1fe
    home: https://github.com/simplyblock-io/spdk-csi
    keywords:
    - spdk
    - csi
    - spdk-csi
    name: spdk-csi
    sources:
    - https://github.com/simplyblock-io/spdk-csi/tree/master/charts/spdk-csi
    urls:
    - https://github.com/simplyblock-io/spdk-csi/raw/master/charts/spdk-csi/v0.3.19/spdk-csi-v0.3.19.tgz
    version: v0.3.19
  - apiVersion: v1
    appVersion: latest
    created: "2025-11-06T19:50:15.638770298Z"
    description: Simplyblock CSI Driver for Kubernetes
    digest: 4ada8f15e1fa50a140ef96146530da44b7aeb8904950f16d3dd75ce4f5a97ed4
    home: https://github.com/simplyblock-io/spdk-csi
    keywords:
    - spdk
    - csi
    - spdk-csi
    name: spdk-csi
    sources:
    - https://github.com/simplyblock-io/spdk-csi/tree/master/charts/spdk-csi
    urls:
    - https://github.com/simplyblock-io/spdk-csi/raw/master/charts/spdk-csi/v0.3.19-patch.1/spdk-csi-v0.3.19-patch.1.tgz
    version: v0.3.19-patch.1
  - apiVersion: v1
    appVersion: latest
    created: "2025-11-06T19:50:15.636811339Z"
    description: Simplyblock CSI Driver for Kubernetes
    digest: 7d2d946f73da4701469cf0bcb569e696fcba0a7e383f94981a6daf126132fc6c
    home: https://github.com/simplyblock-io/spdk-csi
    keywords:
    - spdk
    - csi
    - spdk-csi
    name: spdk-csi
    sources:
    - https://github.com/simplyblock-io/spdk-csi/tree/master/charts/spdk-csi
    urls:
    - https://github.com/simplyblock-io/spdk-csi/raw/master/charts/spdk-csi/v0.3.18/spdk-csi-v0.3.18.tgz
    version: v0.3.18
  - apiVersion: v1
    appVersion: latest
    created: "2025-11-06T19:50:15.635936996Z"
    description: Simplyblock CSI Driver for Kubernetes
    digest: cebe110fd2c3d5f8bd663daede56a9f92fc4e3347d09c80987d3d097e46c87a8
    home: https://github.com/simplyblock-io/spdk-csi
    keywords:
    - spdk
    - csi
    - spdk-csi
    name: spdk-csi
    sources:
    - https://github.com/simplyblock-io/spdk-csi/tree/master/charts/spdk-csi
    urls:
    - https://github.com/simplyblock-io/spdk-csi/raw/master/charts/spdk-csi/v0.3.17/spdk-csi-v0.3.17.tgz
    version: v0.3.17
  - apiVersion: v1
    appVersion: latest
    created: "2025-11-06T19:50:15.635070588Z"
    description: Simplyblock CSI Driver for Kubernetes
    digest: 2f14b7dcbc2c1b9d340b952846182e6eb505223069997b0db42b139d2b1db388
    home: https://github.com/simplyblock-io/spdk-csi
    keywords:
    - spdk
    - csi
    - spdk-csi
    name: spdk-csi
    sources:
    - https://github.com/simplyblock-io/spdk-csi/tree/master/charts/spdk-csi
    urls:
    - https://github.com/simplyblock-io/spdk-csi/raw/master/charts/spdk-csi/v0.3.16/spdk-csi-v0.3.16.tgz
    version: v0.3.16
  - apiVersion: v1
    appVersion: latest
    created: "2025-11-06T19:50:15.634059729Z"
    description: Simplyblock CSI Driver for Kubernetes
    digest: 825c29d045abb878ac14d551d579abe034220d18ead8f074cd42c35851d8e9ad
    home: https://github.com/simplyblock-io/spdk-csi
    keywords:
    - spdk
    - csi
    - spdk-csi
    name: spdk-csi
    sources:
    - https://github.com/simplyblock-io/spdk-csi/tree/master/charts/spdk-csi
    urls:
    - https://github.com/simplyblock-io/spdk-csi/raw/master/charts/spdk-csi/v0.3.15/spdk-csi-v0.3.15.tgz
    version: v0.3.15
  - apiVersion: v1
    appVersion: latest
    created: "2025-11-06T19:50:15.633051617Z"
    description: Simplyblock CSI Driver for Kubernetes
    digest: 33ef4568e8fc1c17c5eb946bde0ce55003f0fa1ab511854efd2e402ff478ab66
    home: https://github.com/simplyblock-io/spdk-csi
    keywords:
    - spdk
    - csi
    - spdk-csi
    name: spdk-csi
    sources:
    - https://github.com/simplyblock-io/spdk-csi/tree/master/charts/spdk-csi
    urls:
    - https://github.com/simplyblock-io/spdk-csi/raw/master/charts/spdk-csi/v0.3.14/spdk-csi-v0.3.14.tgz
    version: v0.3.14
  - apiVersion: v1
    appVersion: latest
    created: "2025-11-06T19:50:15.63131724Z"
    description: Simplyblock CSI Driver for Kubernetes
    digest: 4118557051bc3617840c7cded6599cb7701541a2060b76a8445589f59aa1f0b6
    home: https://github.com/simplyblock-io/spdk-csi
    keywords:
    - spdk
    - csi
    - spdk-csi
    name: spdk-csi
    sources:
    - https://github.com/simplyblock-io/spdk-csi/tree/master/charts/spdk-csi
    urls:
    - https://github.com/simplyblock-io/spdk-csi/raw/master/charts/spdk-csi/v0.3.13/spdk-csi-v0.3.13.tgz
    version: v0.3.13
  - apiVersion: v1
    appVersion: latest
    created: "2025-11-06T19:50:15.630214871Z"
    description: Simplyblock CSI Driver for Kubernetes
    digest: f24ec5f2d3a786966e26604fc1cd6b0b55947acfe54ca7c7654bf2556f73e4e6
    home: https://github.com/simplyblock-io/spdk-csi
    keywords:
    - spdk
    - csi
    - spdk-csi
    name: spdk-csi
    sources:
    - https://github.com/simplyblock-io/spdk-csi/tree/master/charts/spdk-csi
    urls:
    - https://github.com/simplyblock-io/spdk-csi/raw/master/charts/spdk-csi/v0.3.12/spdk-csi-v0.3.12.tgz
    version: v0.3.12
  - apiVersion: v1
    appVersion: latest
    created: "2025-11-06T19:50:15.629238607Z"
    description: Simplyblock CSI Driver for Kubernetes
    digest: 861fd5c8aee948979ac240909ff542ee26174eb9f2cce9ca4c60338a39c7202c
    home: https://github.com/simplyblock-io/spdk-csi
    keywords:
    - spdk
    - csi
    - spdk-csi
    name: spdk-csi
    sources:
    - https://github.com/simplyblock-io/spdk-csi/tree/master/charts/spdk-csi
    urls:
    - https://github.com/simplyblock-io/spdk-csi/raw/master/charts/spdk-csi/v0.3.11/spdk-csi-v0.3.11.tgz
    version: v0.3.11
  - apiVersion: v1
    appVersion: latest
    created: "2025-11-06T19:50:15.628254389Z"
    description: Simplyblock CSI Driver for Kubernetes
    digest: 673e77eebef77f869d92199a841eb1a50669e122fbbaacde9ba6709d098f77e1
    home: https://github.com/simplyblock-io/spdk-csi
    keywords:
    - spdk
    - csi
    - spdk-csi
    name: spdk-csi
    sources:
    - https://github.com/simplyblock-io/spdk-csi/tree/master/charts/spdk-csi
    urls:
    - https://github.com/simplyblock-io/spdk-csi/raw/master/charts/spdk-csi/v0.3.10/spdk-csi-v0.3.10.tgz
    version: v0.3.10
  - apiVersion: v1
    appVersion: latest
    created: "2025-11-06T19:50:15.652513429Z"
    description: Simplyblock CSI Driver for Kubernetes
    digest: 43d9bedad3a6bfa69968423075d67ebc273680446bb6683d4204ef62e1e36c80
    home: https://github.com/simplyblock-io/spdk-csi
    keywords:
    - spdk
    - csi
    - spdk-csi
    name: spdk-csi
    sources:
    - https://github.com/simplyblock-io/spdk-csi/tree/master/charts/spdk-csi
    urls:
    - https://github.com/simplyblock-io/spdk-csi/raw/master/charts/spdk-csi/v0.3.9/spdk-csi-v0.3.9.tgz
    version: v0.3.9
  - apiVersion: v1
    appVersion: latest
    created: "2025-11-06T19:50:15.651587409Z"
    description: Simplyblock CSI Driver for Kubernetes
    digest: 6bce73c847870fe9bd6556d0efef733617a579172f0f6ca48090230b50a04143
    home: https://github.com/simplyblock-io/spdk-csi
    keywords:
    - spdk
    - csi
    - spdk-csi
    name: spdk-csi
    sources:
    - https://github.com/simplyblock-io/spdk-csi/tree/master/charts/spdk-csi
    urls:
    - https://github.com/simplyblock-io/spdk-csi/raw/master/charts/spdk-csi/v0.3.8/spdk-csi-v0.3.8.tgz
    version: v0.3.8
  - apiVersion: v1
    appVersion: latest
    created: "2025-11-06T19:50:15.650675947Z"
    description: Simplyblock CSI Driver for Kubernetes
    digest: e67a2810c0c0825b31ee775ff6b9dabd25ed528ad7758a05fb80d65498f90878
    home: https://github.com/simplyblock-io/spdk-csi
    keywords:
    - spdk
    - csi
    - spdk-csi
    name: spdk-csi
    sources:
    - https://github.com/simplyblock-io/spdk-csi/tree/master/charts/spdk-csi
    urls:
    - https://github.com/simplyblock-io/spdk-csi/raw/master/charts/spdk-csi/v0.3.7/spdk-csi-v0.3.7.tgz
    version: v0.3.7
  - apiVersion: v1
    appVersion: latest
    created: "2025-11-06T19:50:15.649792817Z"
    description: Simplyblock CSI Driver for Kubernetes
    digest: 46ddc4f5f6a982eb470bfaec3c664752a13a5d5d84dc61327aaa1922783404cf
    home: https://github.com/simplyblock-io/spdk-csi
    keywords:
    - spdk
    - csi
    - spdk-csi
    name: spdk-csi
    sources:
    - https://github.com/simplyblock-io/spdk-csi/tree/master/charts/spdk-csi
    urls:
    - https://github.com/simplyblock-io/spdk-csi/raw/master/charts/spdk-csi/v0.3.6/spdk-csi-v0.3.6.tgz
    version: v0.3.6
  - apiVersion: v1
    appVersion: latest
    created: "2025-11-06T19:50:15.648893357Z"
    description: Simplyblock CSI Driver for Kubernetes
    digest: 63091b6ff510f80e554df911b1aaac5847a1346a575a1390b71410490a0f763b
    home: https://github.com/simplyblock-io/spdk-csi
    keywords:
    - spdk
    - csi
    - spdk-csi
    name: spdk-csi
    sources:
    - https://github.com/simplyblock-io/spdk-csi/tree/master/charts/spdk-csi
    urls:
    - https://github.com/simplyblock-io/spdk-csi/raw/master/charts/spdk-csi/v0.3.5/spdk-csi-v0.3.5.tgz
    version: v0.3.5
  - apiVersion: v1
    appVersion: latest
    created: "2025-11-06T19:50:15.647820637Z"
    description: Simplyblock CSI Driver for Kubernetes
    digest: 3a66e531d2879771daeb1498441ac1310fbfb4c8d31ec9c351e9849d004f3aac
    home: https://github.com/simplyblock-io/spdk-csi
    keywords:
    - spdk
    - csi
    - spdk-csi
    name: spdk-csi
    sources:
    - https://github.com/simplyblock-io/spdk-csi/tree/master/charts/spdk-csi
    urls:
    - https://github.com/simplyblock-io/spdk-csi/raw/master/charts/spdk-csi/v0.3.4/spdk-csi-v0.3.4.tgz
    version: v0.3.4
  - apiVersion: v1
    appVersion: latest
    created: "2025-11-06T19:50:15.646408809Z"
    description: Simplyblock CSI Driver for Kubernetes
    digest: b83a89ac558b464eaef296e6317473b7f26514d5a8a7f79aa2acd61da069f3d0
    home: https://github.com/simplyblock-io/spdk-csi
    keywords:
    - spdk
    - csi
    - spdk-csi
    name: spdk-csi
    sources:
    - https://github.com/simplyblock-io/spdk-csi/tree/master/charts/spdk-csi
    urls:
    - https://github.com/simplyblock-io/spdk-csi/raw/master/charts/spdk-csi/v0.3.3/spdk-csi-v0.3.3.tgz
    version: v0.3.3
  - apiVersion: v1
    appVersion: latest
    created: "2025-11-06T19:50:15.639705545Z"
    description: Simplyblock CSI Driver for Kubernetes
    digest: 86b5d9c79c06e8184775c7c41c6dfe175c6f4fa5d0e92910f71e2bf1874858b6
    home: https://github.com/simplyblock-io/spdk-csi
    keywords:
    - spdk
    - csi
    - spdk-csi
    name: spdk-csi
    sources:
    - https://github.com/simplyblock-io/spdk-csi/tree/master/charts/spdk-csi
    urls:
    - https://github.com/simplyblock-io/spdk-csi/raw/master/charts/spdk-csi/v0.3.2/spdk-csi-v0.3.2.tgz
    version: v0.3.2
  - apiVersion: v1
    appVersion: latest
    created: "2025-11-06T19:50:15.627267095Z"
    description: Simplyblock CSI Driver for Kubernetes
    digest: c362b8f3ba046743c11099443b1091b64cb6c27c42aef6b71a483934664a7fde
    home: https://github.com/simplyblock-io/spdk-csi
    keywords:
    - spdk
    - csi
    - spdk-csi
    name: spdk-csi
    sources:
    - https://github.com/simplyblock-io/spdk-csi/tree/master/charts/spdk-csi
    urls:
    - https://github.com/simplyblock-io/spdk-csi/raw/master/charts/spdk-csi/v0.3.1/spdk-csi-v0.3.1.tgz
    version: v0.3.1
  - apiVersion: v1
    appVersion: latest
    created: "2025-11-06T19:50:15.626708682Z"
    description: Simplyblock CSI Driver for Kubernetes
    digest: c7999217b515f9ba4f2a8f5a2a025a3d40d42f21f75af1621043b5a356ab1ac9
    home: https://github.com/simplyblock-io/spdk-csi
    keywords:
    - spdk
    - csi
    - spdk-csi
    name: spdk-csi
    sources:
    - https://github.com/simplyblock-io/spdk-csi/tree/master/charts/spdk-csi
    urls:
    - https://github.com/simplyblock-io/spdk-csi/raw/master/charts/spdk-csi/v0.3.0/spdk-csi-v0.3.0.tgz
    version: v0.3.0
generated: "2025-11-06T19:50:15.625209432Z"
