{{- if .Values.observability.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: simplyblock-grafana-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  MONITORING_SECRET: "{{ .Values.observability.secret }}"
  GRAFANA_ENDPOINT: "{{ .Values.observability.grafana.endpoint }}"

---
apiVersion: v1
kind: Secret
metadata:
  name: simplyblock-graylog-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  GRAYLOG_PASSWORD_SECRET: "{{ .Values.observability.graylog.passwordSecret }}"
  GRAYLOG_ROOT_PASSWORD_SHA2: "{{ .Values.observability.graylog.rootPasswordSha2 }}"
  MAX_NUMBER_OF_INDICES: "{{ .Values.observability.graylog.maxNumberIndex }}"
{{- end }}
