---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-hostpath
  labels:
    app.kubernetes.io/instance: hostpath.csi.k8s.io
    app.kubernetes.io/part-of: csi-driver-host-path
    app.kubernetes.io/name: csi-hostpath-fast
    app.kubernetes.io/component: storageclass
provisioner: hostpath.csi.k8s.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
{{- if .Values.storageclass.allowedTopologyZones }}
allowedTopologies:
- matchLabelExpressions:
  - key: topology.kubernetes.io/zone
    values:
{{- range .Values.storageclass.allowedTopologyZones }}
    - {{ . }}
{{- end }}
{{- end }}
