# SPDX-License-Identifier: Apache-2.0
# Copyright (c) Arm Limited and Contributors
# Copyright (c) Intel Corporation
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: simplyblock-csi-node
  namespace: {{ .Release.Namespace }}
{{ include "spdk.labels" . | indent 2 }}
  annotations:
    {{- with .Values.simplyBlockAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app: simplyblock-csi-node
  template:
    metadata:
{{ include "spdk.labels" . | indent 6 }}
        app: simplyblock-csi-node
      annotations:
        {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
      serviceAccountName: simplyblock-csi-node-sa
      {{- if .Values.node.nodeSelector.create }}
      nodeSelector:
        {{ .Values.node.nodeSelector.key }}: {{ .Values.node.nodeSelector.value }}
      {{- end }}
      hostNetwork: true
      {{- if .Values.node.tolerations.create }}
      tolerations:
      - operator: {{ .Values.node.tolerations.operator }}
        {{- if .Values.node.tolerations.effect }}
        effect: {{ .Values.node.tolerations.effect }}
        {{- end }}
        {{- if .Values.node.tolerations.key }}
        key: {{ .Values.node.tolerations.key }}
        {{- end }}
        {{- if .Values.node.tolerations.value }}
        value: {{ .Values.node.tolerations.value }}
        {{- end }}
      {{- end }}
      containers:
      - name: csi-registrar
        securityContext:
          privileged: true
        image: "{{ .Values.image.nodeDriverRegistrar.repository }}:{{ .Values.image.nodeDriverRegistrar.tag }}"
        imagePullPolicy: {{ .Values.image.nodeDriverRegistrar.pullPolicy }}
        args:
        - "--v=5"
        - "--csi-address=unix:///csi/csi.sock"
        - "--kubelet-registration-path=/var/lib/kubelet/plugins/csi.simplyblock.io/csi.sock"
        - "--health-port=9809"
        ports:
          - containerPort: 9809
            name: healthz
        livenessProbe:
          httpGet:
            path: /healthz
            port: healthz
          initialDelaySeconds: 20
          timeoutSeconds: 10
        volumeMounts:
        - name: socket-dir
          mountPath: /csi
        - name: registration-dir
          mountPath: /registration
      - name: csi-node
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN", "SYS_MODULE"]
          allowPrivilegeEscalation: true
        image: "{{ .Values.image.csi.repository }}:{{ .Values.image.csi.tag }}"
        imagePullPolicy: {{ .Values.image.csi.pullPolicy }}
        args:
        - "--v=5"
        - "--endpoint=unix:///csi/csi.sock"
        - "--nodeid=$(NODE_ID)"
        - "--node"
        env:
        - name: NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        lifecycle:
          postStart:
            exec:
              command:
                [
                  "/bin/sh", "-c",
                  "modprobe nvme-tcp || echo failed to modprobe nvme-tcp && \
                  if [ ! -f /var/lib/nvme/hostid ]; then uuidgen > /var/lib/nvme/hostid; fi && \
                  cp /var/lib/nvme/hostid /etc/nvme/hostid && \
                  echo \"nqn.2014-08.org.nvmexpress:uuid:$(cat /etc/nvme/hostid)\" > /etc/nvme/hostnqn"
                ]
        volumeMounts:
        - name: socket-dir
          mountPath: /csi
        - name: plugin-dir
          mountPath: /var/lib/kubelet/plugins
          mountPropagation: "Bidirectional"
        - name: pod-dir
          mountPath: /var/lib/kubelet/pods
          mountPropagation: "Bidirectional"
        - name: nvme-hostid-dir
          mountPath: /var/lib/nvme
          mountPropagation: "Bidirectional"
        - name: host-dev
          mountPath: /dev
        - name: host-sys
          mountPath: /sys
        - name: csi-nodeserver-config
          mountPath: /etc/spdkcsi-nodeserver-config/
          readOnly: true
        - name: csi-config
          mountPath: /etc/spdkcsi-config/
          readOnly: true
        - name: csi-secret
          mountPath: /etc/spdkcsi-secret/
          readOnly: true
      volumes:
      - name: socket-dir
        hostPath:
          path: /var/lib/kubelet/plugins/csi.simplyblock.io
          type: DirectoryOrCreate
      - name: registration-dir
        hostPath:
          path: /var/lib/kubelet/plugins_registry/
          type: Directory
      - name: plugin-dir
        hostPath:
          path: /var/lib/kubelet/plugins
          type: Directory
      - name: pod-dir
        hostPath:
          path: /var/lib/kubelet/pods
          type: Directory
      - name: nvme-hostid-dir
        hostPath:
          path: /var/lib/nvme
          type: DirectoryOrCreate
      - name: host-dev
        hostPath:
          path: /dev
      - name: host-sys
        hostPath:
          path: /sys
      - name: csi-nodeserver-config
        configMap:
          name: simplyblock-csi-nodeservercm
          optional: true
      - name: csi-config
        configMap:
          name: simplyblock-csi-cm
      - name: csi-secret
        secret:
          secretName: simplyblock-csi-secret-v2
