# SPDX-License-Identifier: Apache-2.0
# Copyright (c) Arm Limited and Contributors
# Copyright (c) Intel Corporation

{{- if .Values.storageclass.create -}}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: simplyblock-csi-sc
provisioner: csi.simplyblock.io
parameters:
  csi.storage.k8s.io/fstype: ext4
  pool_name: {{ .Values.logicalVolume.pool_name }}
  qos_rw_iops: "{{ .Values.logicalVolume.qos_rw_iops }}"
  qos_rw_mbytes: "{{ .Values.logicalVolume.qos_rw_mbytes }}"
  qos_r_mbytes: "{{ .Values.logicalVolume.qos_r_mbytes }}"
  qos_w_mbytes: "{{ .Values.logicalVolume.qos_w_mbytes }}"
  compression: "{{ .Values.logicalVolume.compression }}"
  encryption: "{{ .Values.logicalVolume.encryption }}"
  distr_ndcs: "{{ .Values.logicalVolume.numDataChunks }}"
  distr_npcs: "{{ .Values.logicalVolume.numParityChunks }}"
  lvol_priority_class: "{{ .Values.logicalVolume.lvol_priority_class }}"
  nspv: "{{ .Values.logicalVolume.nspv }}"
  tune2fs_reserved_blocks: "{{ .Values.logicalVolume.tune2fs_reserved_blocks }}"
  cluster_id: "{{ .Values.csiConfig.simplybk.uuid }}"
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: simplyblock-csi-sc-cache
provisioner: csi.simplyblock.io
parameters:
  csi.storage.k8s.io/fstype: ext4
  type: cache
  pool_name: "{{ .Values.logicalVolume.pool_name }}"
  qos_rw_iops: "{{ .Values.logicalVolume.qos_rw_iops }}"
  qos_rw_mbytes: "{{ .Values.logicalVolume.qos_rw_mbytes }}"
  qos_r_mbytes: "{{ .Values.logicalVolume.qos_r_mbytes }}"
  qos_w_mbytes: "{{ .Values.logicalVolume.qos_w_mbytes }}"
  compression: "{{ .Values.logicalVolume.compression }}"
  encryption: "{{ .Values.logicalVolume.encryption }}"
  distr_ndcs: "{{ .Values.logicalVolume.numDataChunks }}"
  distr_npcs: "{{ .Values.logicalVolume.numParityChunks }}"
  lvol_priority_class: "{{ .Values.logicalVolume.lvol_priority_class }}"
  nspv: "{{ .Values.logicalVolume.nspv }}"
  tune2fs_reserved_blocks: "{{ .Values.logicalVolume.tune2fs_reserved_blocks }}"
  cluster_id: "{{ .Values.csiConfig.simplybk.uuid }}"
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true

{{- end -}}
